src/app/maze/clean/[slug]/page.tsx
src/app/maze/dirty/[slug]/page.tsx
src/app/mystery/clean/ [slug]/page.tsx
src/app/mystery/dirty/ [slug]/page.tsx
src/app/page.tsx
src/app/prologue/guest/ [slug]/page.tsx
src/app/prologue/host/ [slug]/page.tsx
src/app/waiting_room/guest/ [slug]/page.tsx
src/app/waiting_room/host/ [slug]/page.tsx
src/app/waiting_room/page.tsx

/misery-frontend
|-- /src/app
|-- /ending
|     |--/clean/ [slug]/ page.tsx
|     |--/dirty/ [slug]/ page.tsx
|--/maze
|   |--/clean/ [slug]/ page.tsx
|   |--/dirty/ [slug]/ page.tsx
|--/mystery
|     |--/clean/ [slug]/ page.tsx
|     |--/dirty/ [slug]/ page.tsx
|--/prologue
|     |--/guest/ [slug]/ page.tsx
|     |--/host/ [slug]/ page.tsx
|--/waiting_room
|     |--/guest/ [slug]/ page.tsx
|     |--/host/ [slug]/ page.tsx
page.tsx 
上記のようにディレクトリ構成を変更しました。

ディレクトリ構成を変更

---

src/app/mystery_temp/clean/page.tsx
src/app/mystery_temp/dirty/page.tsx

- app/mystery_temp/clean/page.tsx
- app/mystery_temp/dirty/page.tsx

mystery_tempという一時作業ディレクトリを作成

---

src/app/mystery/dirty/[slug]/page.tsx

以下の３つの作業を統合
・相手のドアの鍵を開ける
・アイテムボタンの設置と、メッセージウィンドウが出て、アイテムが取得できる仕組み
・家具視点と壁の穴視点の切り替え

dirty部屋のアイテム取得と左右切り替えの作業を統合

---

src/app/globals.css

globals.cssの反映

---

src/app/mystery_temp/clean/page.tsx
src/app/mystery_temp/dirty/page.tsx

- アイテムリストの選択・解除の実装
- アイテム間の連動を実装
上記の二つの実装をしていない状態

アイテムリストの選択及びアイテム間の連動を実装

---

src/app/mystery_temp/clean_zakky/page.tsx

脱出ゲームのコードのマージ中（仮反映）

---

src/app/mystery_temp/clean_zakky/page.tsx

脱出ゲームのコードマージ 進捗報告

---

src/app/mystery_temp/clean_zakky/page.tsx

プログラムのマージ中

---

src/app/mystery_temp/clean_zakky/page.tsx

```
const backgrounds: Background[] = [
{ id: 1, path: '/dirty_room.png', name: 'room1' },
{ id: 2, path: '/wall.png', name: 'room2' },
{ id: 3, path: '/dark.png', name: 'room3' },
];
```
背景画像が
id: 1の場合は、▶️のみ表示
id: 2の場合は、◀️のみ表示
するよう修正。

view側で矢印の表示を制御するコードを追加

---

src/app/mystery/clean/[slug]/page.tsx
src/app/mystery/dirty/[slug]/page.tsx

アイテムを選択した状態で壁の穴をクリックしたら、自分のところのアイテムが消えて、相手のアイテムリストに追加されるようにした。両方の部屋でできる。

プレイヤー間のアイテムの受け渡しを実装

---

src/app/mystery_temp/clean_zakky/page.tsx

アイテムリスト内で銃を選択した状態で、itemsのid:5の壁をクリックするとbackgrounds配列のid:3の背景を表示する。

アイテムリストで銃を選択した状態で特定の処理を発生させる仕組み

---

src/app/waiting_room/components/WaitingRoomButton.module.css

guest側のwaiting_roomの最後の注意書きのCSS修正をpushし忘れたので再度pushしました。

guest側のwaiting_roomのCSS修正

---

src/app/prologue/guest/[slug]/page.tsx
src/app/prologue/host/[slug]/page.tsx

prologueのguest/hostの導入文を作成しました。

prologueのguest/hostの導入文作成

---

src/app/ending/clean/[slug]/page.tsx
src/app/ending/dirty/[slug]/page.tsx

endingのclean・dirtyの文章作成

---

src/app/maze/clean/[slug]/page.tsx
src/app/maze/dirty/[slug]/page.tsx

要素Eにマウスがいくとタイムアタックが発生する。双方向通信も確認ずみ。

迷路の整理とタイムアタックの処理を追加

---

src/app/maze/clean/[slug]/page.tsx

mazeのcleanを改良

---

package-lock.json
package.json

package.jsonのインストール

---

src/app/credits/true/page.tsx
src/app/ending/true/page.tsx
src/app/maze/clean/[slug]/page.tsx
src/app/maze/dirty/[slug]/page.tsx

`const [newsPaperState, setNewsPaperState] = useState(true);`及び関連するコードの実装
`const [newsPaperState, setNewsPaperState] = useState(true);`
`const hideNewspaper = () => {
setNewsPaperState(false);
};`及び関連するコードの実装
ending/true/page.tsx
credits/true/page.tsx

新聞紙のギミック実装及びTrueエンドの実装

---

src/app/credits/clean/[slug]/page.tsx
src/app/credits/dirty/[slug]/page.tsx
src/app/credits/true/page.tsx
src/app/globals.css

trueエンドの実装

---

package-lock.json
package.json
postcss.config.js

npm install postcss-nesting --save-devを実行
postcss-nestingプラグインを追加

postcss-nestingを追加

---

src/app/page.tsx

howtoplayのフォントが変わらない問題を修正

---

src/app/page.tsx

howtoplayの修正
